import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,Check,ChevronRight,Image,FileText,Database,ScanText,Sparkles,ShieldCheck,WalletCards,LogOut} from 'lucide-react';
import {supabase} from './lib/supabase';
import './styles.css';

const TASK_TYPES={image:{label:'Image verification',icon:Image},text:{label:'Text verification',icon:FileText},data:{label:'Data verification',icon:Database},ocr:{label:'OCR verification',icon:ScanText}};

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[view,setView]=useState('home'),[task,setTask]=useState(null),[remaining,setRemaining]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadTask()},[session]);
 async function loadTask(){setError('');const {data,error}=await supabase.rpc('get_next_task');if(error){setError(error.message);return}if(data?.status==='NO_TASKS'){setTask(null);setRemaining(data.remaining??0);setView('dashboard');return}setTask(data);setRemaining(data.remaining??null);setView('task')}
 async function submit(answer){if(!task)return;setError('');const {data,error}=await supabase.rpc('submit_task_answer',{p_assignment_id:task.assignment_id,p_answer:answer});if(error){setError(error.message);return}setRemaining(data?.remaining??null);if(data?.status==='BATCH_COMPLETE'){setTask(null);setView('unlock')}else await loadTask()}
 async function signOut(){await supabase.auth.signOut();setView('home')}
 if(loading)return <Shell><div className="loading">Loading secure session…</div></Shell>;
 if(!supabase)return <Shell><main className="container centered"><div className="card notice"><span className="eyebrow">CONFIGURATION REQUIRED</span><h2>Connect Supabase</h2><p>Add the two VITE_SUPABASE environment variables to your deployment.</p></div></main></Shell>;
 if(!session&&view==='auth')return <Auth onBack={()=>setView('home')} onSuccess={()=>setView('dashboard')}/>;
 if(!session)return <Home onStart={()=>setView('auth')}/>;
 if(view==='task'&&task)return <Task task={task} remaining={remaining} error={error} onBack={()=>setView('dashboard')} onSubmit={submit}/>;
 if(view==='unlock')return <Unlock onBack={()=>setView('dashboard')} error={error} onRequest={()=>setError('Rewarded-ad unlocking is disabled until an ad provider and format that explicitly permits incentivized traffic is configured.')}/>;
 return <Dashboard remaining={remaining} error={error} onTask={loadTask} onSignOut={signOut}/>;
}
function Shell({children}){return <div className="shell"><header className="nav"><div className="brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div><span className="secure"><span/> Secure</span></header>{children}<footer>TaskFlow · Verified human data work</footer></div>}
function Home({onStart}){return <Shell><main className="container home"><section className="hero card"><div><span className="eyebrow">HUMAN DATA VERIFICATION</span><h1>Small tasks.<br/><em>Useful data.</em></h1><p>Verify images, text, data and OCR with simple decisions. Start with a controlled task batch and build a quality record.</p><button className="primary" onClick={onStart}>Continue with phone <ChevronRight size={18}/></button></div><div className="hero-art"><div className="floating a">YES</div><div className="hero-center"><ShieldCheck size={28}/><b>Verified work</b><small>Quality-first task flow</small></div><div className="floating b">NO</div></div></section></main></Shell>}
function Auth({onBack,onSuccess}){const [phone,setPhone]=useState(''),[otp,setOtp]=useState(['','','','','','']),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){setError('');const n=phone.replace(/\D/g,'');if(n.length!==10){setError('Enter a valid 10-digit Indian mobile number.');return}setBusy(true);const {error}=await supabase.auth.signInWithOtp({phone:'+91'+n});setBusy(false);if(error)setError(error.message);else setSent(true)}
 async function verify(){setError('');setBusy(true);const {error}=await supabase.auth.verifyOtp({phone:'+91'+phone.replace(/\D/g,''),token:otp.join(''),type:'sms'});setBusy(false);if(error)setError(error.message);else onSuccess()}
 function setDigit(i,v){const d=v.replace(/\D/g,'').slice(-1),next=[...otp];next[i]=d;setOtp(next);if(d&&i<5)document.getElementById('otp-'+(i+1))?.focus()}
 return <Shell><main className="auth-wrap"><div className="card auth"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><div className="brand auth-brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div>{!sent?<><span className="eyebrow">PHONE SIGN IN</span><h2>Welcome back.</h2><p>Use your phone number to securely create an account or sign in.</p><label>Mobile number</label><div className="phone"><b>+91</b><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="98765 43210"/></div><button className="primary full" disabled={busy} onClick={send}>{busy?'Sending…':'Send OTP'}<ChevronRight size={18}/></button></>:<><span className="eyebrow">VERIFY</span><h2>Enter your code.</h2><p>We sent a verification code to <b>+91 {phone}</b>.</p><div className="otp">{otp.map((v,i)=><input key={i} id={'otp-'+i} value={v} maxLength={1} inputMode="numeric" onChange={e=>setDigit(i,e.target.value)}/>)}</div><button className="primary full" disabled={busy||otp.join('').length!==6} onClick={verify}>{busy?'Verifying…':'Verify & continue'}<Check size={18}/></button><button className="link" onClick={()=>setSent(false)}>Change number</button></>} {error&&<div className="error">{error}</div>}<small>By continuing you agree to the Terms and Privacy Policy.</small></div></main></Shell>}
function Dashboard({remaining,error,onTask,onSignOut}){return <Shell><main className="container"><div className="dashboard-head"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Ready when you are.</h2></div><button className="icon-btn" onClick={onSignOut}><LogOut size={18}/></button></div><div className="dash-grid"><div className="card balance"><div className="icon-box"><WalletCards size={20}/></div><span className="muted">Available balance</span><strong>₹0.00</strong><small>Rewards become available only after verified task completion.</small></div><div className="card tasks"><div className="task-head"><span className="eyebrow">TASK QUEUE</span><span className="count">{remaining??'—'}</span></div><h3>Verified data tasks</h3><p>Each task uses either YES/NO or four fixed options. No manual task picking is required.</p><button className="primary" onClick={onTask}>Get next task <ChevronRight size={18}/></button></div></div>{error&&<div className="error">{error}</div>}</main></Shell>}
function Task({task,remaining,error,onBack,onSubmit}){const meta=TASK_TYPES[task.task_type]||TASK_TYPES.data,Icon=meta.icon;return <Shell><main className="container task-page"><div className="task-top"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><span>{remaining??'—'} tasks remaining</span></div><div className="progress"><span style={{width:'8%'}}/></div><section className="card task-card"><div className="type"><Icon size={15}/>{meta.label}</div>{task.asset_url?<img className="asset" src={task.asset_url} alt="Task input"/>:<div className="asset-placeholder"><Icon size={30}/><span>Source content</span></div>}<h1>{task.prompt}</h1>{task.answer_mode==='yes_no'?<div className="answers two"><button onClick={()=>onSubmit('YES')}><Check/>YES</button><button onClick={()=>onSubmit('NO')}><span className="x">×</span>NO</button></div>:<div className="answers">{(task.options||[]).map((o,i)=><button key={i} onClick={()=>onSubmit(String.fromCharCode(65+i))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>}{error&&<div className="error">{error}</div>}</section></main></Shell>}
function Unlock({onBack,onRequest,error}){return <Shell><main className="auth-wrap"><div className="card unlock"><div className="success"><Check size={30}/></div><span className="eyebrow">BATCH COMPLETE</span><h2>Ready for more?</h2><p>The next task batch will become available through the approved rewarded-ad unlock system.</p><button className="primary full" onClick={onRequest}>Unlock next tasks <ChevronRight size={18}/></button><button className="link" onClick={onBack}>Back to dashboard</button>{error&&<div className="error">{error}</div>}</div></main></Shell>}
createRoot(document.getElementById('root')).render(<App/>);