import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,Check,ChevronRight,Image,FileText,Database,ScanText,Sparkles,ShieldCheck,WalletCards,LogOut,Clock3,UserCheck,X,RefreshCw} from 'lucide-react';
import {supabase} from './lib/supabase';
import './styles.css';

const TASK_TYPES={image:{label:'Image verification',icon:Image},text:{label:'Text verification',icon:FileText},data:{label:'Data verification',icon:Database},ocr:{label:'OCR verification',icon:ScanText}};

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[view,setView]=useState(window.location.pathname==='/admin'?'admin':'home'),[task,setTask]=useState(null),[remaining,setRemaining]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(null);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&!session.user.is_anonymous)loadStatus();else if(session)loadStatus();},[session]);
 async function loadStatus(){setError('');const {data,error}=await supabase.rpc('get_my_activation_status');if(error){setError(error.message);return}setStatus(data);if(data?.status==='approved')setView(window.location.pathname==='/admin'?'admin':'dashboard');else if(data?.status==='rejected')setView('rejected');else setView(window.location.pathname==='/admin'?'admin':'pending')}
 async function loadTask(){setError('');const {data,error}=await supabase.rpc('get_next_task');if(error){setError(error.message);return}if(data?.status==='PENDING_ACTIVATION'){setStatus(s=>({...s,status:'pending'}));setView('pending');return}if(data?.status==='NO_TASKS'){setTask(null);setRemaining(data.remaining??0);setView('dashboard');return}setTask(data);setRemaining(data.remaining??null);setView('task')}
 async function submit(answer){if(!task)return;setError('');const {data,error}=await supabase.rpc('submit_task_answer',{p_assignment_id:task.assignment_id,p_answer:answer});if(error){setError(error.message);return}setRemaining(data?.remaining??null);if(data?.status==='BATCH_COMPLETE'){setTask(null);setView('unlock')}else await loadTask()}
 async function signOut(){await supabase.auth.signOut();setSession(null);setStatus(null);setTask(null);setView('home')}
 if(loading)return <Shell><div className="loading">Loading secure session…</div></Shell>;
 if(!supabase)return <Shell><main className="container centered"><div className="card notice"><span className="eyebrow">CONFIGURATION REQUIRED</span><h2>Connect Supabase</h2><p>Add the two VITE_SUPABASE environment variables to your deployment.</p></div></main></Shell>;
 if(view==='admin')return <AdminGate session={session} onBack={()=>{window.history.replaceState({},'', '/');setView(session?'pending':'home')}}/>;
 if(!session&&view==='auth')return <Auth onBack={()=>setView('home')} onSuccess={(s)=>{setSession(s);setView('pending')}}/>;
 if(!session)return <Home onStart={()=>setView('auth')}/>;
 if(view==='task'&&task)return <Task task={task} remaining={remaining} error={error} onBack={()=>setView('dashboard')} onSubmit={submit}/>;
 if(view==='unlock')return <Unlock onBack={()=>setView('dashboard')} error={error} onRequest={()=>setError('Rewarded-ad unlocking is disabled until an approved provider and format that explicitly permits incentivized traffic is configured.')}/>;
 if(view==='rejected')return <Rejected onSignOut={signOut}/>;
 if(view==='pending')return <Pending status={status} onRefresh={loadStatus} onSignOut={signOut}/>;
 return <Dashboard remaining={remaining} error={error} onTask={loadTask} onSignOut={signOut}/>;
}
function Shell({children}){return <div className="shell"><header className="nav"><div className="brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div><span className="secure"><span/> Secure</span></header>{children}<footer>TaskFlow · Verified human data work</footer></div>}
function Home({onStart}){return <Shell><main className="container home"><section className="hero card"><div><span className="eyebrow">HUMAN DATA VERIFICATION</span><h1>Small tasks.<br/><em>Useful data.</em></h1><p>Apply with your name and mobile number. Every account is reviewed manually before task access is activated.</p><button className="primary" onClick={onStart}>Apply for access <ChevronRight size={18}/></button></div><div className="hero-art"><div className="floating a">PENDING</div><div className="hero-center"><ShieldCheck size={28}/><b>Manual approval</b><small>Quality-first access</small></div><div className="floating b">VERIFIED</div></div></section></main></Shell>}
function Auth({onBack,onSuccess}){const [name,setName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(){setError('');const cleanName=name.trim().replace(/\s+/g,' '),n=phone.replace(/\D/g,'');if(cleanName.length<2||cleanName.length>80){setError('Enter your full name.');return}if(n.length!==10){setError('Enter a valid 10-digit Indian mobile number.');return}setBusy(true);let {data:authData,error:authError}=await supabase.auth.getSession();if(!authData.session){const r=await supabase.auth.signInAnonymously();authData=r.data;authError=r.error}if(authError){setBusy(false);setError(authError.message);return}const {data,error}=await supabase.rpc('submit_activation_request',{p_name:cleanName,p_phone:'+91'+n});setBusy(false);if(error){setError(error.message);return}onSuccess(authData.session||data?.session)}
 return <Shell><main className="auth-wrap"><div className="card auth"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><div className="brand auth-brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div><span className="eyebrow">ACCESS REQUEST</span><h2>Join TaskFlow.</h2><p>Enter your name and mobile number. There is no OTP at this stage. An admin will review your application before activation.</p><label>Full name</label><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" autoComplete="name"/><label className="field-label">Mobile number</label><div className="phone"><b>+91</b><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="98765 43210"/></div><button className="primary full" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit application'}<ChevronRight size={18}/></button>{error&&<div className="error">{error}</div>}<small>Your application is stored securely. Task access remains locked until manual approval.</small></div></main></Shell>}
function Pending({status,onRefresh,onSignOut}){return <Shell><main className="auth-wrap"><div className="card unlock pending-card"><div className="pending-icon"><Clock3 size={30}/></div><span className="eyebrow">ACCOUNT WAITING</span><h2>Pending activation.</h2><p>Your application has been received. An admin will review your account manually. You cannot receive tasks or rewards until the account is approved.</p><div className="status-box"><span>Applicant</span><b>{status?.name||'—'}</b><span>Mobile</span><b>{status?.phone||'—'}</b><span>Status</span><b className="status-pending">Pending review</b></div><button className="primary full" onClick={onRefresh}><RefreshCw size={17}/> Check status</button><button className="link" onClick={onSignOut}>Leave this device</button></div></main></Shell>}
function Rejected({onSignOut}){return <Shell><main className="auth-wrap"><div className="card unlock"><div className="rejected-icon"><X size={30}/></div><span className="eyebrow">ACCESS NOT ACTIVATED</span><h2>Application not approved.</h2><p>Your application is not currently approved for TaskFlow. Contact the administrator if you believe this is incorrect.</p><button className="primary full" onClick={onSignOut}>Return to start</button></div></main></Shell>}
function Dashboard({remaining,error,onTask,onSignOut}){return <Shell><main className="container"><div className="dashboard-head"><div><span className="eyebrow">YOUR WORKSPACE</span><h2>Ready when you are.</h2></div><button className="icon-btn" onClick={onSignOut}><LogOut size={18}/></button></div><div className="dash-grid"><div className="card balance"><div className="icon-box"><WalletCards size={20}/></div><span className="muted">Available balance</span><strong>₹0.00</strong><small>Rewards become available only after verified task completion.</small></div><div className="card tasks"><div className="task-head"><span className="eyebrow">TASK QUEUE</span><span className="count">{remaining??'—'}</span></div><h3>Verified data tasks</h3><p>Each task uses either YES/NO or four fixed options. No manual task picking is required.</p><button className="primary" onClick={onTask}>Get next task <ChevronRight size={18}/></button></div></div>{error&&<div className="error">{error}</div>}</main></Shell>}
function Task({task,remaining,error,onBack,onSubmit}){const meta=TASK_TYPES[task.task_type]||TASK_TYPES.data,Icon=meta.icon;return <Shell><main className="container task-page"><div className="task-top"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><span>{remaining??'—'} tasks remaining</span></div><div className="progress"><span style={{width:'8%'}}/></div><section className="card task-card"><div className="type"><Icon size={15}/>{meta.label}</div>{task.asset_url?<img className="asset" src={task.asset_url} alt="Task input"/>:<div className="asset-placeholder"><Icon size={30}/><span>Source content</span></div>}<h1>{task.prompt}</h1>{task.answer_mode==='yes_no'?<div className="answers two"><button onClick={()=>onSubmit('YES')}><Check/>YES</button><button onClick={()=>onSubmit('NO')}><span className="x">×</span>NO</button></div>:<div className="answers">{(task.options||[]).map((o,i)=><button key={i} onClick={()=>onSubmit(String.fromCharCode(65+i))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>}{error&&<div className="error">{error}</div>}</section></main></Shell>}
function Unlock({onBack,onRequest,error}){return <Shell><main className="auth-wrap"><div className="card unlock"><div className="success"><Check size={30}/></div><span className="eyebrow">BATCH COMPLETE</span><h2>Ready for more?</h2><p>The next task batch will become available through the approved rewarded-ad unlock system.</p><button className="primary full" onClick={onRequest}>Unlock next tasks <ChevronRight size={18}/></button><button className="link" onClick={onBack}>Back to dashboard</button>{error&&<div className="error">{error}</div>}</div></main></Shell>}
function AdminGate({session,onBack}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authorized,setAuthorized]=useState(false);
 useEffect(()=>{if(session&&!session.user.is_anonymous)checkAdmin()},[session]);
 async function checkAdmin(){const {data,error}=await supabase.rpc('is_current_user_admin');if(error){setError(error.message);return}setAuthorized(Boolean(data))}
 async function login(){setError('');setBusy(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setError(error.message);return}const {data:ok,error:e}=await supabase.rpc('is_current_user_admin');if(e||!ok){await supabase.auth.signOut();setError('This account is not an administrator.');return}setAuthorized(true)}
 if(authorized)return <AdminPanel onBack={onBack}/>;
 return <Shell><main className="auth-wrap"><div className="card auth"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><span className="eyebrow">ADMIN CONSOLE</span><h2>Review applications.</h2><p>Sign in with the separate Supabase admin account.</p><label>Email</label><input className="field" value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username"/><label className="field-label">Password</label><input className="field" value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password"/><button className="primary full" disabled={busy} onClick={login}>{busy?'Signing in…':'Admin sign in'}<ChevronRight size={18}/></button>{error&&<div className="error">{error}</div>}</div></main></Shell>}
function AdminPanel({onBack}){const [rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');const {data,error}=await supabase.rpc('list_activation_requests');if(error)setError(error.message);else setRows(data||[]);setBusy(false)}
 useEffect(()=>{load()},[]);
 async function decide(id,decision){setError('');const {error}=await supabase.rpc('set_activation_status',{p_user_id:id,p_status:decision});if(error){setError(error.message);return}await load()}
 async function logout(){await supabase.auth.signOut();window.location.href='/admin'}
 return <Shell><main className="container admin-page"><div className="dashboard-head"><div><span className="eyebrow">ADMIN CONSOLE</span><h2>Activation queue.</h2></div><div className="admin-actions"><button className="icon-btn" onClick={load}><RefreshCw size={18}/></button><button className="icon-btn" onClick={logout}><LogOut size={18}/></button></div></div>{error&&<div className="error">{error}</div>}{busy?<div className="card admin-empty">Loading applications…</div>:rows.length===0?<div className="card admin-empty"><UserCheck size={28}/><h3>No pending applications</h3><p>New applications will appear here.</p></div>:<div className="admin-list">{rows.map(r=><div className="card admin-row" key={r.id}><div><span className="eyebrow">{new Date(r.created_at).toLocaleString()}</span><h3>{r.name}</h3><p>{r.phone}</p></div><div className="admin-row-actions"><button className="approve" onClick={()=>decide(r.id,'approved')}><Check size={16}/> Approve</button><button className="reject" onClick={()=>decide(r.id,'rejected')}><X size={16}/> Reject</button></div></div>)}</div>}</main></Shell>}
createRoot(document.getElementById('root')).render(<App/>);
