import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft,Check,ChevronRight,Image,FileText,Database,ScanText,Sparkles,ShieldCheck,WalletCards,LogOut,Clock3,UserCheck,X,RefreshCw,Users,Layers3,IndianRupee,Activity,CircleAlert,Play,ClipboardCheck} from 'lucide-react';
import {supabase} from './lib/supabase';
import './styles.css';

const TASK_TYPES={image:{label:'Image verification',icon:Image},text:{label:'Text verification',icon:FileText},data:{label:'Data verification',icon:Database},ocr:{label:'OCR verification',icon:ScanText}};

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[view,setView]=useState(window.location.pathname==='/admin'?'admin':'home'),[authMode,setAuthMode]=useState('register'),[task,setTask]=useState(null),[remaining,setRemaining]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(null),[profile,setProfile]=useState(null),[submitting,setSubmitting]=useState(false),[lastResult,setLastResult]=useState(null);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&view!=='admin')loadStatus();},[session]);
 async function loadStatus(){
  setError('');
  const {data,error}=await supabase.rpc('get_my_activation_status');
  if(error){setError(error.message);return}
  setStatus(data);
  if(data?.status==='approved'){
   await loadProfile();
   setView('dashboard');
  }else if(data?.status==='rejected')setView('rejected');
  else setView('pending');
 }
 async function loadProfile(){
  if(!session?.user?.id)return;
  const {data,error}=await supabase.from('profiles').select('available_balance,task_credits,quality_score').eq('id',session.user.id).single();
  if(!error)setProfile(data);
 }
 async function loadTask(){
  setError('');
  const {data,error}=await supabase.rpc('get_next_task');
  if(error){setError(error.message);return}
  if(data?.status==='PENDING_ACTIVATION'){setStatus(s=>({...s,status:'pending'}));setView('pending');return}
  if(data?.status==='NO_TASKS'){
   setTask(null);setRemaining(data.remaining??profile?.task_credits??0);setError(data.message||'No verified tasks are available right now. The task queue is empty.');await loadProfile();return;
  }
  setTask(data);setRemaining(data.remaining??null);setError('');setView('task');
 }
 async function submit(answer){
  if(!task||submitting)return;
  setError('');
  setSubmitting(true);
  const {data,error}=await supabase.rpc('submit_task_answer',{p_assignment_id:task.assignment_id,p_answer:answer});
  if(error){
   setSubmitting(false);
   setError([error.message,error.details,error.hint].filter(Boolean).join(' · '));
   return;
  }
  setLastResult({correct:Boolean(data?.correct),reward:Number(data?.reward||0),balance:Number(data?.available_balance||0)});
  setRemaining(data?.remaining??null);
  await loadProfile();
  setSubmitting(false);
  if(data?.status==='BATCH_COMPLETE'){setTask(null);setView('unlock')}else await loadTask();
 }
 async function signOut(){await supabase.auth.signOut();setSession(null);setStatus(null);setProfile(null);setTask(null);setView('home')}
 if(loading)return <Shell><div className="loading">Loading secure session…</div></Shell>;
 if(!supabase)return <Shell><main className="container centered"><div className="card notice"><span className="eyebrow">CONFIGURATION REQUIRED</span><h2>Connect Supabase</h2><p>Add the two VITE_SUPABASE environment variables to your deployment.</p></div></main></Shell>;
 if(view==='admin')return <AdminGate session={session} onBack={()=>{window.history.replaceState({},'', '/');setView(session?'pending':'home')}}/>;
 if(!session&&view==='auth')return <Auth mode={authMode} onBack={()=>setView('home')} onModeChange={setAuthMode} onSuccess={(s)=>{setSession(s);setView('pending')}}/>;
 if(!session)return <Home onStart={mode=>{setAuthMode(mode);setView('auth')}}/>;
 if(view==='task'&&task)return <Task task={task} remaining={remaining} error={error} result={lastResult} submitting={submitting} onBack={()=>{setError('');setLastResult(null);setView('dashboard')}} onSubmit={submit}/>;
 if(view==='unlock')return <Unlock onBack={()=>setView('dashboard')} error={error} onRequest={()=>setError('More tasks are released only through an approved, verified unlock provider. No ad is being simulated.')}/>;
 if(view==='rejected')return <Rejected onSignOut={signOut}/>;
 if(view==='pending')return <Pending status={status} onRefresh={loadStatus} onSignOut={signOut}/>;
 return <Dashboard profile={profile} remaining={remaining} error={error} onTask={loadTask} onRefresh={loadProfile} onSignOut={signOut}/>;
}

function Shell({children,showFooter=true}){return <div className="shell"><header className="nav"><div className="brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div><span className="secure"><span/> Secure</span></header>{children}{showFooter&&<footer><div className="footer-quote">“Simple tasks. Clear rewards. Work when you’re ready.”</div><div className="footer-copy">TaskFlow helps people complete short data tasks and build earnings from approved work.</div><div className="footer-links"><span>Flexible task work</span><span>Fast answer checks</span><span>Transparent balance</span></div><small>© TaskFlow · Task-based earning platform</small></footer>}</div>}

function Home({onStart}){return <Shell><main className="container home"><section className="hero card"><div className="hero-copy"><span className="eyebrow">EARN FROM SHORT DATA TASKS</span><h1>Small tasks.<br/><em>Real earning.</em></h1><p>Complete simple image, text, data and OCR verification tasks. Your reward is added to your balance after the answer is checked.</p><div className="hero-actions"><button className="primary" onClick={()=>onStart('register')}>Register <ChevronRight size={18}/></button><button className="secondary" onClick={()=>onStart('login')}>Login</button></div><div className="trust-row"><span><Check size={15}/> Clear task rewards</span><span><Check size={15}/> Flexible work</span><span><Check size={15}/> Secure balance</span></div></div><div className="hero-art"><div className="earn-card"><span className="earn-label">YOUR EARNINGS</span><strong>₹0.01</strong><small>Example reward per correct task</small><div className="earn-line"><span/><span/><span/><span/></div></div><div className="floating a">TASK +₹</div><div className="floating b">PAID</div></div></section><section className="earning-strip"><div><span className="eyebrow">HOW IT WORKS</span><h2>From signup to earning.</h2></div><div className="steps"><div><b>01</b><strong>Register</strong><span>Create your account with your name, mobile number and password.</span></div><div><b>02</b><strong>Get approved</strong><span>Your application is reviewed before earning access is opened.</span></div><div><b>03</b><strong>Complete tasks</strong><span>Answer short verification tasks across four task categories.</span></div><div><b>04</b><strong>Build your balance</strong><span>Correct, validated work adds rewards to your account balance.</span></div></div></section><section className="task-types"><div><span className="eyebrow">TASK TYPES</span><h2>Work that stays simple.</h2><p>Choose from short verification tasks designed to be easy to understand and quick to complete.</p></div><div className="type-grid"><div className="mini-card"><Image size={19}/><b>Image</b><span>Check what an image contains.</span></div><div className="mini-card"><FileText size={19}/><b>Text</b><span>Verify simple text statements.</span></div><div className="mini-card"><Database size={19}/><b>Data</b><span>Confirm structured information.</span></div><div className="mini-card"><ScanText size={19}/><b>OCR</b><span>Verify text extracted from images.</span></div></div></section><section className="worker-note card"><div><span className="eyebrow">FOR EVERYDAY EARNERS</span><h2>Less complexity.<br/>More focus on the task.</h2></div><p>No confusing dashboards or complicated work queues. Register, get approved, complete the work available to you, and watch your validated rewards accumulate.</p></section></main></Shell>}

function Auth({mode,onBack,onModeChange,onSuccess}){const [name,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const isRegister=mode==='register';
 async function submit(){setError('');const cleanName=name.trim().replace(/\s+/g,' '),n=phone.replace(/\D/g,'');if(isRegister&&(cleanName.length<2||cleanName.length>80)){setError('Enter your full name.');return}if(n.length!==10){setError('Enter a valid 10-digit Indian mobile number.');return}if(password.length<8){setError('Password must be at least 8 characters.');return}setBusy(true);if(isRegister){const {data,error:authError}=await supabase.auth.signUp({phone:'+91'+n,password,options:{data:{name:cleanName}}});if(authError){setBusy(false);setError(authError.message);return}if(!data.session){setBusy(false);setError('Registration is not active yet. In Supabase Auth, phone confirmation must be disabled because TaskFlow does not use OTP.');return}const {error:requestError}=await supabase.rpc('submit_activation_request',{p_name:cleanName,p_phone:'+91'+n});setBusy(false);if(requestError){setError(requestError.message);return}onSuccess(data.session);}else{const {data,error:authError}=await supabase.auth.signInWithPassword({phone:'+91'+n,password});setBusy(false);if(authError){setError(authError.message);return}onSuccess(data.session);}}
 return <Shell><main className="auth-wrap"><div className="card auth"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><div className="brand auth-brand"><span className="mark"><Sparkles size={17}/></span>TaskFlow</div><div className="auth-switch"><button className={isRegister?'active':''} onClick={()=>{setError('');onModeChange('register')}}>Register</button><button className={!isRegister?'active':''} onClick={()=>{setError('');onModeChange('login')}}>Login</button></div><span className="eyebrow">{isRegister?'CREATE YOUR EARNING ACCOUNT':'WELCOME BACK'}</span><h2>{isRegister?'Start earning with TaskFlow.':'Log in to your TaskFlow account.'}</h2><p>{isRegister?'Create your account, get approved, then complete short verification tasks to build your balance.':'Use your registered mobile number and password to continue.'}</p>{isRegister&&<><label>Full name</label><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" autoComplete="name"/></>}<label className={isRegister?'field-label':''}>Mobile number</label><div className="phone"><b>+91</b><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" placeholder="98765 43210" autoComplete="tel"/></div><label className="field-label">Password</label><input className="field" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="At least 8 characters" autoComplete={isRegister?'new-password':'current-password'}/><button className="primary full" disabled={busy} onClick={submit}>{busy?(isRegister?'Creating account…':'Signing in…'):(isRegister?'Register':'Login')}<ChevronRight size={18}/></button>{error&&<div className="error">{error}</div>}<small>{isRegister?'No OTP. Your application is reviewed before task access is activated.':'Your balance and task history stay linked to your account.'}</small></div></main></Shell>}

function Pending({status,onRefresh,onSignOut}){return <Shell><main className="auth-wrap"><div className="card unlock pending-card"><div className="pending-icon"><Clock3 size={30}/></div><span className="eyebrow">ACCOUNT WAITING</span><h2>Pending activation.</h2><p>Your application has been received. An admin will review your account manually. You cannot receive tasks or rewards until the account is approved.</p><div className="status-box"><span>Applicant</span><b>{status?.name||'—'}</b><span>Mobile</span><b>{status?.phone||'—'}</b><span>Status</span><b className="status-pending">Pending review</b></div><button className="primary full" onClick={onRefresh}><RefreshCw size={17}/> Check status</button><button className="link" onClick={onSignOut}>Leave this device</button></div></main></Shell>}

function Rejected({onSignOut}){return <Shell><main className="auth-wrap"><div className="card unlock"><div className="rejected-icon"><X size={30}/></div><span className="eyebrow">ACCESS NOT ACTIVATED</span><h2>Application not approved.</h2><p>Your application is not currently approved for TaskFlow. Contact the administrator if you believe this is incorrect.</p><button className="primary full" onClick={onSignOut}>Return to start</button></div></main></Shell>}

function Dashboard({profile,remaining,error,onTask,onRefresh,onSignOut}){const credits=remaining??profile?.task_credits??0;return <Shell><main className="container"><div className="dashboard-head"><div><span className="eyebrow">YOUR EARNINGS</span><h2>Ready to earn.</h2></div><div className="head-actions"><button className="icon-btn" onClick={onRefresh} title="Refresh"><RefreshCw size={18}/></button><button className="icon-btn" onClick={onSignOut} title="Sign out"><LogOut size={18}/></button></div></div><div className="dash-grid"><div className="card balance"><div className="icon-box"><WalletCards size={20}/></div><span className="muted">Available balance</span><strong>₹{Number(profile?.available_balance||0).toFixed(2)}</strong><small>Rewards are added after your answers are checked.</small></div><div className="card tasks"><div className="task-head"><span className="eyebrow">AVAILABLE TASKS</span><span className="count">{credits}</span></div><h3>Complete short tasks</h3><p>Answer simple image, text, data and OCR checks. Correct answers add rewards to your balance.</p><button className="primary" onClick={onTask}><Play size={16}/> Get next task <ChevronRight size={18}/></button>{error&&<div className="queue-warning"><CircleAlert size={17}/><div><b>Task queue status</b><span>{error}</span></div></div>}</div></div></main></Shell>}

function Task({task,remaining,error,result,submitting,onBack,onSubmit}){const meta=TASK_TYPES[task.task_type]||TASK_TYPES.data,Icon=meta.icon;return <Shell><main className="container task-page"><div className="task-top"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><span>{remaining??'—'} tasks remaining</span></div><div className="progress"><span style={{width:'8%'}}/></div><section className="card task-card"><div className="type"><Icon size={15}/>{meta.label}</div>{task.asset_url?<img className="asset" src={task.asset_url} alt="Task input" onError={(e)=>{e.currentTarget.style.display='none';e.currentTarget.parentElement?.classList.add('asset-error')}}/>:<div className="asset-placeholder"><Icon size={30}/><span>{task.task_type==='image'?'Image unavailable':'Text/source content'}</span></div>}<h1>{task.prompt}</h1>{task.answer_mode==='yes_no'?<div className="answers two"><button disabled={submitting} onClick={()=>onSubmit('YES')}><Check/>YES</button><button disabled={submitting} onClick={()=>onSubmit('NO')}><span className="x">×</span>NO</button></div>:<div className="answers">{(task.options||[]).map((o,i)=><button disabled={submitting} key={i} onClick={()=>onSubmit(String.fromCharCode(65+i))}><b>{String.fromCharCode(65+i)}</b>{o}</button>)}</div>}{submitting&&<div className="queue-warning"><RefreshCw size={17}/><div><b>Validating answer…</b><span>Your answer is being checked on the server.</span></div></div>}{result&&<div className="success"><Check size={18}/><span>{result.correct?'Correct — ₹'+result.reward.toFixed(2)+' credited.':'Answer recorded. No reward for this answer.'}</span></div>}{error&&<div className="error">{error}</div>}</section></main></Shell>}
function Unlock({onBack,onRequest,error}){return <Shell><main className="auth-wrap"><div className="card unlock"><div className="success"><Check size={30}/></div><span className="eyebrow">BATCH COMPLETE</span><h2>Ready for more?</h2><p>Your current task batch is complete. More tasks will appear when they are available for your account.</p><button className="primary full" onClick={onRequest}>Check for more tasks <RefreshCw size={17}/></button><button className="link" onClick={onBack}>Back to dashboard</button>{error&&<div className="error">{error}</div>}</div></main></Shell>}

function AdminGate({session,onBack}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authorized,setAuthorized]=useState(false);
 useEffect(()=>{if(session&&!session.user.is_anonymous)checkAdmin()},[session]);
 async function checkAdmin(){const {data,error}=await supabase.rpc('is_current_user_admin');if(error){setError(error.message);return}setAuthorized(Boolean(data))}
 async function login(){setError('');setBusy(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setError(error.message);return}const {data:ok,error:e}=await supabase.rpc('is_current_user_admin');if(e||!ok){await supabase.auth.signOut();setError('This account is not an administrator.');return}setAuthorized(true)}
 if(authorized)return <AdminPanel onBack={onBack}/>;
 return <Shell><main className="auth-wrap"><div className="card auth"><button className="icon-btn" onClick={onBack}><ArrowLeft size={18}/></button><span className="eyebrow">ADMIN CONSOLE</span><h2>Control center.</h2><p>Sign in with the separate permanent Supabase administrator account.</p><label>Email</label><input className="field" value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username"/><label className="field-label">Password</label><input className="field" value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password"/><button className="primary full" disabled={busy} onClick={login}>{busy?'Signing in…':'Open admin console'}<ChevronRight size={18}/></button>{error&&<div className="error">{error}</div>}</div></main></Shell>}

function AdminPanel({onBack}){const [rows,setRows]=useState([]),[stats,setStats]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');const [requests,overview]=await Promise.all([supabase.rpc('list_activation_requests'),supabase.rpc('get_admin_overview')]);if(requests.error)setError(requests.error.message);else setRows(requests.data||[]);if(overview.error&&!requests.error)setError(overview.error.message);else setStats(overview.data||null);setBusy(false)}
 useEffect(()=>{load()},[]);
 async function decide(id,decision){setError('');const {error}=await supabase.rpc('set_activation_status',{p_user_id:id,p_status:decision});if(error){setError(error.message);return}await load()}
 async function logout(){await supabase.auth.signOut();window.location.href='/admin'}
 return <Shell><main className="container admin-page"><div className="admin-hero"><div><span className="eyebrow">ADMIN CONTROL CENTER</span><h2>Operate TaskFlow.</h2><p>Review applicants, monitor the live task inventory, and see whether the earning pipeline is actually ready.</p></div><div className="admin-actions"><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={18}/></button><button className="icon-btn" onClick={logout} title="Sign out"><LogOut size={18}/></button></div></div>{error&&<div className="error">{error}</div>}<div className="admin-stats"><Stat icon={Users} label="Pending applications" value={stats?.pending_applications??rows.length} tone="amber"/><Stat icon={Layers3} label="Active tasks" value={stats?.active_tasks??0} tone="blue"/><Stat icon={ClipboardCheck} label="Completed tasks" value={stats?.completed_tasks??0} tone="green"/><Stat icon={IndianRupee} label="Rewards issued" value={'₹'+Number(stats?.rewards_issued||0).toFixed(2)} tone="dark"/></div><section className="admin-section"><div className="section-head"><div><span className="eyebrow">ACCESS</span><h3>Activation queue</h3></div><span className="section-status"><span className="live-dot"/>Live</span></div>{busy?<div className="card admin-empty">Loading control-center data…</div>:rows.length===0?<div className="card admin-empty"><UserCheck size={28}/><h3>No pending applications</h3><p>New applications will appear here automatically.</p></div>:<div className="admin-list">{rows.map(r=><div className="card admin-row" key={r.id}><div className="applicant"><div className="avatar">{(r.name||'?').slice(0,1).toUpperCase()}</div><div><span className="eyebrow">{new Date(r.created_at).toLocaleString()}</span><h3>{r.name}</h3><p>{r.phone}</p></div></div><div className="admin-row-actions"><button className="approve" onClick={()=>decide(r.id,'approved')}><Check size={16}/> Approve</button><button className="reject" onClick={()=>decide(r.id,'rejected')}><X size={16}/> Reject</button></div></div>)}</div>}</section><section className="admin-pipeline"><div className="pipeline-icon"><Activity size={20}/></div><div><span className="eyebrow">TASK PIPELINE</span><h3>{Number(stats?.active_tasks||0)>0?'Tasks are available to users.':'No verified task inventory yet.'}</h3><p>{Number(stats?.active_tasks||0)>0?'The Get next task flow has an active supply to draw from.':'This is why an approved user currently sees the dashboard instead of a task. The next build step is the licensed ingestion worker that imports, validates, deduplicates, and publishes tasks.'}</p></div></section></main></Shell>}
function Stat({icon:Icon,label,value,tone}){return <div className={'card stat-card '+tone}><div className="stat-icon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong></div>}

createRoot(document.getElementById('root')).render(<App/>);
